name: Rust Sanity

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Format Check
      working-directory: llmsh
      run: cargo fmt --check
    - name: Build
      working-directory: llmsh
      run: cargo build --verbose
    - name: Run tests
      working-directory: llmsh
      run: cargo test --verbose
